name: 'Recognize Change Notification Action'
description: 'Get notified when a specific file is changed.'
inputs:
    notification-type:
        description: 'Type of notification. Currently, only email is supported.'
        required: true
        default: 'email'
    path:
        description: 'File or directory to track for changes.'
        required: true
    mail-connection-url:
        description: 'Mail connection URL (smtp+starttls://user:password@server:port, smtp://user:password@server:port).'
        required: true
    mail-subject:
        description: 'Subject of the mail that will be send upon a change.'
        required: true
    mail-from:
        description: 'From which mail address the notification will be sent.'
        required: true
    mail-to:
        description: 'The mail addresses that should receive the notification (separated by a comma).'
        required: true

runs:
    using: 'composite'
    steps:
        - uses: actions/checkout@v3
          name: Checkout files
          with:
              fetch-depth: 0
        - name: Get changed files
          id: changed-files
          uses: tj-actions/changed-files@v3
          with:
              separator: ','
        - name: Send email notification
          if: ${{ contains(inputs.path, 'Fiberworkz.Backend/Controllers/FWAppFormsController.cs Fiberworkz.Backend/Models/TaskTypeMappingDTO.cs Fiberworkz.DataChangeEngine.Tests/Parsers/EnumParserTests.cs Fiberworkz.DataChangeEngine.Tests/Serializers/EnumSerializerTests.cs Fiberworkz.DataChangeEngine/EntityReader.cs Fiberworkz.DataChangeEngine/Parsers/AdministratorTypeParser.cs Fiberworkz.DataChangeEngine/Serializers/AdministratorTypeSerializer.cs Fiberworkz.DataChangeEngine/Serializers/BooleanSerializer.cs Fiberworkz.DataChangeEngine/Serializers/BuildTypeSerializer.cs Fiberworkz.DataChangeEngine/Serializers/BuildingTypeSerializer.cs Fiberworkz.DataChangeEngine/Serializers/CableTypeSerializer.cs Fiberworkz.DataChangeEngine/Serializers/ConnectionTypeSerializer.cs Fiberworkz.DataChangeEngine/Serializers/ConnectorTypeSerializer.cs Fiberworkz.DataChangeEngine/Serializers/FTULocationSerializer.cs Fiberworkz.DataChangeEngine/Serializers/FWTaskStatusSerializer.cs Fiberworkz.DataChangeEngine/Serializers/ISerializer.cs Fiberworkz.DataChangeEngine/Serializers/NetworkTypeSerializer.cs Fiberworkz.DataChangeEngine/Serializers/ProjectStatusSerializer.cs Fiberworkz.Database/Enums/TaskTypeMappingType.cs Fiberworkz.Database/Migrations/20221021094934_AddTaskTypeMappingType.Designer.cs Fiberworkz.Database/Migrations/20221021094934_AddTaskTypeMappingType.cs Fiberworkz.Database/Migrations/FiberworkzDbContextModelSnapshot.cs Fiberworkz.Database/Models/TaskTypeMapping.cs Fiberworkz.Frontend/ClientApp/src/app/components/management/management-form-mapping-details/management-form-mapping-details.component.html Fiberworkz.Frontend/ClientApp/src/app/components/management/management-form-mapping-details/management-form-mapping-details.component.ts Fiberworkz.Frontend/ClientApp/src/assets/i18n/nl.json Fiberworkz.Frontend/ClientApp/src/models/task-type-mapping-type.enum.ts Fiberworkz.Frontend/ClientApp/src/models/task-type-mapping.model.ts Fiberworkz.Functions/Functions/PushTasksToFWApp.cs') && inputs.notification-type == 'email' }}
          uses: dawidd6/action-send-mail@v3
          with:
              connection_url: ${{ inputs.mail-connection-url }}
              subject: ${{ inputs.mail-subject }}
              from: ${{ inputs.mail-from }}
              to: ${{ inputs.mail-to }}
              body: |-
                  # ${{ inputs.mail-subject }}
                  The path ${{ inputs.path }} has been changed. To see the changes, please visit the following link:
                  [${{ github.event.repository.html_url }}/commit/${{ github.sha }}](${{ github.event.repository.html_url }}/commit/${{ github.sha }})
              convert_markdown: true

